-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'USER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE 'RESTAURANT_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'RESTAURANT_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE 'CUSTOMER_ANONYMIZED';
